import logo from '../assets/logo.png';
import logo_oac from '../assets/logo_oac.png';
import logo_of from '../assets/logo_of.png';
import spid from '../assets/spid.png';
import soac from '../assets/soac.png';
import sos from '../assets/sos.png';
import l_oac from '../assets/l_oac.png';
import l_hpid from '../assets/l_hpid.png';
import l_of from '../assets/l_of.png';
import hero_pic from '../assets/pexels-fauxels-3183165.jpg';
import oflt from '../assets/oflt.png';
import hero_pic2 from '../assets/BackgroundEraser_20230902_200641448.png';
import spid2 from '../assets/spid2.png';
import soac2 from '../assets/soac2.png';
import sos2 from '../assets/sos2.png';
import sof from '../assets/sof.png';
import sof2 from '../assets/sof2.png';
import logo_hpid from '../assets/logo_hpid.png';
import lhpid from '../assets/lhpid.png';
import about_pic from '../assets/pexels-fauxels-3182774.jpg';

export default { logo, logo_oac, logo_of, logo_hpid, spid, spid2, soac, soac2, sos, sos2, sof, sof2, l_oac, l_hpid, l_of, hero_pic, hero_pic2, oflt, lhpid, about_pic };